site_name: USTC 系统程序设计基础
theme:
  custom_dir: overrides
  name: material
  language: 'zh'
  features:
    - navigation.tabs     # 启用上方的分栏
    - navigation.tabs.sticky  # 让分栏保持可见
    - navigation.expand   # 启用左侧导航栏的展开按钮
    - navigation.footer   # 启用界面下方翻页按钮
    - content.code.copy   # 启用代码框复制按钮

  icon:
    # 对应网址为 https://fontawesome.com/
    logo: fontawesome/solid/computer
    repo: fontawesome/brands/github

  palette:
    - scheme: 'default'
      primary: 'purple'
      accent: 'purple'
      toggle:
        icon: material/weather-sunny
        name: 切换到夜晚模式
    - scheme: 'slate'
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: 切换到白天模式

plugins:
  - search
  - glightbox
  - git-authors   # 显示作者 https://github.com/timvink/mkdocs-git-authors-plugin
  - git-revision-date-localized   # 显示上次编辑时间 https://github.com/timvink/mkdocs-git-revision-date-localized-plugin






markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - admonition
  - pymdownx.keys
  - footnotes

  - pymdownx.blocks.admonition: # 不同风格的提示块
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode

extra_css:
  - stylesheets/extra.css
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - styles.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

nav:
  - 首页: index.md
  - Lab1:
    - Linux基础: lab1/index.md
    - 在虚拟机下安装Linux系统: lab1/part1.md
    - 初探Linux: lab1/part2.md
    - WSL2: lab1/additional.md
    #- 实验要求与检查: lab1/requirement.md
  - Lab2:
    - Make&CMake&Git介绍: lab2/index.md
    - Make工具: lab2/part1.md
    - CMake工具: lab2/part2.md
    - Git工具: lab2/part3.md
    - Git 与 CMake 基础实践操作指南: lab2/experiment-guide.md
    #- 实验要求与检查: lab2/requirement.md
  - Lab3:
    - 模块化程序设计: lab3/index.md
    - 单词整理器: lab3/problem1_word_cleaner.md
    - 成绩行筛选器: lab3/problem2_score_filter.md 
    - 动态通讯录: lab3/problem3_phonebook.md
  - Lab4:
    - 指针的高级使用: lab4/index.md
    - LRU 缓存: lab4/LRU_Cache.md
  - Lab5:
    - 代码的优化: lab5/index.md
    - 图像卷积性能优化: lab5/Image_Convolution_Optimization.md